<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\inventaris;
class InventarisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    private $mesin = [
        [
            [
                'nama' => 'JEMBATAN TIMBANG CPO',
                'nomor_mesin' => '1',
                'merek' => 'AVERY',
                'type' => null,
                'kapasitas' => '50 Ton',
                'tahun_perolehan' => '1985',
                'nomor_inventaris' => '220000005223',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'JEMBATAN TIMBANG TBS',
                'nomor_mesin' => '2',
                'merek' => 'CV Natal Inti',
                'type' => null,
                'kapasitas' => '50 Ton',
                'tahun_perolehan' => '2010',
                'nomor_inventaris' => '220000005228',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '90',
            ],
            [
                'nama' => 'JEMBATAN TIMBANG Inti',
                'nomor_mesin' => '3',
                'merek' => 'Tunas Jaya',
                'type' => null,
                'kapasitas' => '50 Ton',
                'tahun_perolehan' => '1997',
                'nomor_inventaris' => '220000005511',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
        ],
        [
            [
                'nama' => 'Loading Ramp',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Kompartment',
                'kapasitas' => '15 pintu (@ 15 ton TBS)',
                'tahun_perolehan' => '2010',
                'nomor_inventaris' => '220000005230',
                'nilai_aktiva' => '1.364.066.076',
                'kondisi_mesin' => '69',
            ],
            [
                'nama' => 'Loading Ramp',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => 'Kompartment',
                'kapasitas' => '20 pintu (@ 15 ton TBS)',
                'tahun_perolehan' => '1989',
                'nomor_inventaris' => '220000005224',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '35',
            ],
            [
                'nama' => 'Transfer Carriage',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Mobile',
                'kapasitas' => '3 lori (@2,5 ton TBS)',
                'tahun_perolehan' => '2021',
                'nomor_inventaris' => '220000005251',
                'nilai_aktiva' => ' 106.356.833 ',
                'kondisi_mesin' => '80',
            ],
        ],
        [
            [
                'nama' => 'Sterilizer no.1',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Horizontal',
                'kapasitas' => '10 lori (25 ton TBS)',
                'tahun_perolehan' => '2007',
                'nomor_inventaris' => '220000005247',
                'nilai_aktiva' => '415.339.355',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Sterilizer no.2',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => 'Horizontal',
                'kapasitas' => '10 lori (25 ton TBS)',
                'tahun_perolehan' => '2007',
                'nomor_inventaris' => '220000005249',
                'nilai_aktiva' => '406.621.440',
                'kondisi_mesin' => '55',
            ],
            [
                'nama' => 'Sterilizer no.3',
                'nomor_mesin' => '3',
                'merek' => null,
                'type' => 'Horizontal',
                'kapasitas' => '10 lori (25 ton TBS)',
                'tahun_perolehan' => '2011',
                'nomor_inventaris' => '220000005254',
                'nilai_aktiva' => '876.515.325',
                'kondisi_mesin' => '85',
            ],
            [
                'nama' => 'Jembatan Cantilever Buah Mentah',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Mobile Cantilever',
                'kapasitas' => '1 lori (2,5 ton TBS)',
                'tahun_perolehan' => '2021',
                'nomor_inventaris' => '220000015111',
                'nilai_aktiva' => ' 58.308.333 ',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Jembatan Cantilever Buah Masak',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => 'Mobile Cantilever',
                'kapasitas' => '1 lori (2,5 ton TBS)',
                'tahun_perolehan' => '2021',
                'nomor_inventaris' => null,
                'nilai_aktiva' => null,
                'kondisi_mesin' => null,
            ],
            [
                'nama' => 'Blowdown Silencer',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Vertikal',
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2020',
                'nomor_inventaris' => '220000014093',
                'nilai_aktiva' => '253.918.133',
                'kondisi_mesin' => '65',
            ],
            [
                'nama' => 'Blowup Silencer',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Vertikal',
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2021',
                'nomor_inventaris' => '220000014866',
                'nilai_aktiva' => '95.707.794',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Tracklier Pengisian Lori',
                'nomor_mesin' => '4',
                'merek' => null,
                'type' => null,
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2007',
                'nomor_inventaris' => '220000005250',
                'nilai_aktiva' => '40.693.743',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Tracklier Lori Rebusan',
                'nomor_mesin' => '5',
                'merek' => null,
                'type' => null,
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2010',
                'nomor_inventaris' => '220000005253',
                'nilai_aktiva' => '64.687.667',
                'kondisi_mesin' => '65',
            ],
            [
                'nama' => 'Tracklier Buah Masak',
                'nomor_mesin' => '1',
                'merek' => 'Brevini',
                'type' => null,
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2021',
                'nomor_inventaris' => '220000014854',
                'nilai_aktiva' => '178.206.718',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Tracklier Buah Masak',
                'nomor_mesin' => '2',
                'merek' => 'Brevini',
                'type' => null,
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '1991',
                'nomor_inventaris' => '220000005237',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '65',
            ],
            [
                'nama' => 'Tracklier Buah Masak',
                'nomor_mesin' => '3',
                'merek' => null,
                'type' => null,
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '1993',
                'nomor_inventaris' => '220000005238',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '65',
            ],
        ],
        [
            [
                'nama' => 'Hoisting Crane',
                'nomor_mesin' => '1',
                'merek' => 'Demag',
                'type' => 'Travelling Crane',
                'kapasitas' => '5 ton ',
                'tahun_perolehan' => '1987',
                'nomor_inventaris' => '220000005270',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '69',
            ],
            [
                'nama' => 'Hoisting Crane',
                'nomor_mesin' => '2',
                'merek' => 'Demag',
                'type' => 'Travelling Crane',
                'kapasitas' => '5 ton ',
                'tahun_perolehan' => '2009',
                'nomor_inventaris' => '220000005282',
                'nilai_aktiva' => '265.775.510',
                'kondisi_mesin' => '69',
            ],
            [
                'nama' => 'Thresher ',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Tromol dengan autofeeder sistem scrapper',
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2011',
                'nomor_inventaris' => '220000005466',
                'nilai_aktiva' => '341.377.674',
                'kondisi_mesin' => '85',
            ],
            [
                'nama' => 'Thresher ',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => null,
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2013',
                'nomor_inventaris' => '220000005539',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '85',
            ],
            [
                'nama' => 'Thresher ',
                'nomor_mesin' => '3',
                'merek' => null,
                'type' => null,
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2000',
                'nomor_inventaris' => '220000005275',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '85',
            ],
            [
                'nama' => 'Bunch Crusher',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Double Screw',
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2018',
                'nomor_inventaris' => '220000005298',
                'nilai_aktiva' => '124.883.625',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Empty Bunch Conveyor',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Scrapper',
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2021',
                'nomor_inventaris' => '220000015020',
                'nilai_aktiva' => '345.833.333',
                'kondisi_mesin' => '85',
            ],
            [
                'nama' => 'Bottom Cross Conveyor',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Conveyor',
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2021',
                'nomor_inventaris' => '220000014934',
                'nilai_aktiva' => '89.098.125',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Top Cross Conveyor',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Conveyor',
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2016',
                'nomor_inventaris' => '220000005289',
                'nilai_aktiva' => '18.307.255',
                'kondisi_mesin' => '69',
            ],
        ],
        [
            [
                'nama' => 'Digester no.1',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Vertikal',
                'kapasitas' => '15 ton TBS/jam',
                'tahun_perolehan' => '2012',
                'nomor_inventaris' => '220000005320',
                'nilai_aktiva' => '410.978.333',
                'kondisi_mesin' => '65',
            ],
            [
                'nama' => 'Digester no.2',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => 'Vertikal',
                'kapasitas' => '15 ton TBS/jam',
                'tahun_perolehan' => '2007',
                'nomor_inventaris' => '220000005316',
                'nilai_aktiva' => '195.644.360',
                'kondisi_mesin' => '85',
            ],
            [
                'nama' => 'Digester no.3',
                'nomor_mesin' => '3',
                'merek' => null,
                'type' => 'Vertikal',
                'kapasitas' => '15 ton TBS/jam',
                'tahun_perolehan' => '2004',
                'nomor_inventaris' => '220000015796',
                'nilai_aktiva' => '121.596.794',
                'kondisi_mesin' => '85',
            ],
            [
                'nama' => 'Digester no.4',
                'nomor_mesin' => '4',
                'merek' => null,
                'type' => 'Vertikal',
                'kapasitas' => '15 ton TBS/jam',
                'tahun_perolehan' => '2004',
                'nomor_inventaris' => '220000015797',
                'nilai_aktiva' => '121.552.912',
                'kondisi_mesin' => '85',
            ],
            [
                'nama' => 'Screw Press no.1',
                'nomor_mesin' => '1',
                'merek' => 'Apindo',
                'type' => 'Continous Double Screw',
                'kapasitas' => '15 ton TBS/jam',
                'tahun_perolehan' => '2020',
                'nomor_inventaris' => '220000014097',
                'nilai_aktiva' => '605.820.625',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Screw Press no.2',
                'nomor_mesin' => '2',
                'merek' => 'Apindo',
                'type' => 'Continous Double Screw',
                'kapasitas' => '15 ton TBS/jam',
                'tahun_perolehan' => '2012',
                'nomor_inventaris' => '220000005320',
                'nilai_aktiva' => '410.978.333',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Screw Press no.3',
                'nomor_mesin' => '3',
                'merek' => 'Apindo',
                'type' => 'Continous Double Screw',
                'kapasitas' => '15 ton TBS/jam',
                'tahun_perolehan' => '2014',
                'nomor_inventaris' => '220000005533',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Screw Press no.4',
                'nomor_mesin' => '4',
                'merek' => 'CB',
                'type' => 'Continous Double Screw',
                'kapasitas' => '15 ton TBS/jam',
                'tahun_perolehan' => '2007',
                'nomor_inventaris' => '220000005316',
                'nilai_aktiva' => '195.644.360',
                'kondisi_mesin' => '68',
            ],
            [
                'nama' => 'Inverter Screw Press',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => 'Inverter',
                'kapasitas' => null,
                'tahun_perolehan' => '2016',
                'nomor_inventaris' => '220000005313',
                'nilai_aktiva' => '12.844.045',
                'kondisi_mesin' => '35',
            ],
            [
                'nama' => 'Inverter Screw Press',
                'nomor_mesin' => '3',
                'merek' => null,
                'type' => 'Inverter',
                'kapasitas' => null,
                'tahun_perolehan' => '2016',
                'nomor_inventaris' => '220000005314',
                'nilai_aktiva' => '12.844.045',
                'kondisi_mesin' => '35',
            ],
            [
                'nama' => 'Conveyor Distribusi Digester',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Conveyor',
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2020',
                'nomor_inventaris' => '220000014378',
                'nilai_aktiva' => '139.946.435',
                'kondisi_mesin' => '65',
            ],
        ],
        [
            [
                'nama' => 'Vibrating Screen',
                'nomor_mesin' => '1',
                'merek' => 'Tapis',
                'type' => 'Ayakan Getar',
                'kapasitas' => '15 m3 / jam',
                'tahun_perolehan' => '2017',
                'nomor_inventaris' => '220000005548',
                'nilai_aktiva' => '65.803.125',
                'kondisi_mesin' => '70',
            ],
            [
                'nama' => 'Vibrating Screen',
                'nomor_mesin' => '2',
                'merek' => 'Jinsheng',
                'type' => 'Ayakan Getar',
                'kapasitas' => '15 m3 / jam',
                'tahun_perolehan' => '2020',
                'nomor_inventaris' => '220000014098',
                'nilai_aktiva' => '109.940.104',
                'kondisi_mesin' => '65',
            ],
            [
                'nama' => 'Bak Raw Oil',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => null,
                'kapasitas' => '15 m3 / jam',
                'tahun_perolehan' => '2009',
                'nomor_inventaris' => '220000005284',
                'nilai_aktiva' => '74.450.308',
                'kondisi_mesin' => '65',
            ],
            [
                'nama' => 'Continous Settling Tank',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Vertical Settling Tank',
                'kapasitas' => '90 ton',
                'tahun_perolehan' => '2011',
                'nomor_inventaris' => '220000005381',
                'nilai_aktiva' => '346.939.570',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Continous Settling Tank',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => 'Vertical Settling Tank',
                'kapasitas' => '90 ton',
                'tahun_perolehan' => '2000',
                'nomor_inventaris' => '220000005364',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Oil Tank',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Tanki Vertikal',
                'kapasitas' => '10 ton',
                'tahun_perolehan' => '2012',
                'nomor_inventaris' => '220000005397',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Oil Tank',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => 'Tanki Vertikal',
                'kapasitas' => '10 ton',
                'tahun_perolehan' => '1975',
                'nomor_inventaris' => '220000005335',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Sludge Tank',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Tanki Vertikal',
                'kapasitas' => '10 ton',
                'tahun_perolehan' => '1975',
                'nomor_inventaris' => '220000005334',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Sludge Tank',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => 'Tanki Vertikal',
                'kapasitas' => '10 ton',
                'tahun_perolehan' => '2012',
                'nomor_inventaris' => '220000005398',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'PreCleaner',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Automatic Flushing',
                'kapasitas' => '15 ton Sludge / jam',
                'tahun_perolehan' => '2019',
                'nomor_inventaris' => '220000013762',
                'nilai_aktiva' => '244.007.812',
                'kondisi_mesin' => '69',
            ],
            [
                'nama' => 'PreCleaner',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => 'Automatic Flushing',
                'kapasitas' => '15 ton Sludge / jam',
                'tahun_perolehan' => '2022',
                'nomor_inventaris' => '220000015692',
                'nilai_aktiva' => '217.218.750',
                'kondisi_mesin' => '95',
            ],
            [
                'nama' => 'Decanter',
                'nomor_mesin' => '1',
                'merek' => 'IHI',
                'type' => '3 phase',
                'kapasitas' => '15 ton Sludge / jam',
                'tahun_perolehan' => '2013',
                'nomor_inventaris' => '220000005386',
                'nilai_aktiva' => '1.782.505.337',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Decanter',
                'nomor_mesin' => '2',
                'merek' => 'IHI',
                'type' => '3 phase',
                'kapasitas' => '15 ton Sludge / jam',
                'tahun_perolehan' => '2016',
                'nomor_inventaris' => '220000005549',
                'nilai_aktiva' => '2.287.116.447',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Oil Purifier',
                'nomor_mesin' => '1',
                'merek' => 'West Lake',
                'type' => null,
                'kapasitas' => '4,5 M3/J',
                'tahun_perolehan' => '2012',
                'nomor_inventaris' => '220000005374',
                'nilai_aktiva' => '189.396.480',
                'kondisi_mesin' => '60',
            ],
            [
                'nama' => 'Oil Purifier',
                'nomor_mesin' => '2',
                'merek' => 'West Lake',
                'type' => null,
                'kapasitas' => '4,5 M3/J',
                'tahun_perolehan' => '1993',
                'nomor_inventaris' => '220000005352',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '25',
            ],
            [
                'nama' => 'Oil Purifier',
                'nomor_mesin' => '3',
                'merek' => 'West Lake',
                'type' => null,
                'kapasitas' => '4,5 M3/J',
                'tahun_perolehan' => '1999',
                'nomor_inventaris' => '220000005363',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '25',
            ],
            [
                'nama' => 'Oil Purifier',
                'nomor_mesin' => '4',
                'merek' => 'West Lake',
                'type' => null,
                'kapasitas' => '4,5 M3/J',
                'tahun_perolehan' => '2007',
                'nomor_inventaris' => '220000005373',
                'nilai_aktiva' => '80.128.525',
                'kondisi_mesin' => '60',
            ],
            [
                'nama' => 'Vacuum Drier',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => null,
                'kapasitas' => '15 ton/jam',
                'tahun_perolehan' => '2011',
                'nomor_inventaris' => '220000005377',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '60',
            ],
            [
                'nama' => 'Vacuum Drier',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => null,
                'kapasitas' => '15 ton/jam',
                'tahun_perolehan' => '2012',
                'nomor_inventaris' => '220000005396',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '70',
            ],
        ],
        [
            [
                'nama' => 'CBC',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => null,
                'kapasitas' => '30 ton TBS / jam',
                'tahun_perolehan' => '2009',
                'nomor_inventaris' => '220000005408',
                'nilai_aktiva' => '105.539.375',
                'kondisi_mesin' => '90',
            ],
            [
                'nama' => 'CBC',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => null,
                'kapasitas' => '30 ton TBS / jam',
                'tahun_perolehan' => '2021',
                'nomor_inventaris' => '900000000175',
                'nilai_aktiva' => '266.777.000',
                'kondisi_mesin' => '75',
            ],
            [
                'nama' => 'Polishing Drum',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Drum Putar',
                'kapasitas' => '30 ton TBS / jam',
                'tahun_perolehan' => '2022',
                'nomor_inventaris' => null,
                'nilai_aktiva' => null,
                'kondisi_mesin' => '90',
            ],
            [
                'nama' => 'Polishing Drum',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => 'Drum Putar',
                'kapasitas' => '30 ton TBS / jam',
                'tahun_perolehan' => '2017',
                'nomor_inventaris' => '220000005557',
                'nilai_aktiva' => '41.315.440',
                'kondisi_mesin' => '65',
            ],
            [
                'nama' => 'Depericarper',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => null,
                'kapasitas' => '30 ton TBS / jam',
                'tahun_perolehan' => '2006',
                'nomor_inventaris' => '220000005406',
                'nilai_aktiva' => '104.374.201',
                'kondisi_mesin' => '90',
            ],
            [
                'nama' => 'Depericarper',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => null,
                'kapasitas' => '30 ton TBS / jam',
                'tahun_perolehan' => '2009',
                'nomor_inventaris' => '220000005416',
                'nilai_aktiva' => '238.971.250',
                'kondisi_mesin' => '90',
            ],
            [
                'nama' => 'Fibre Cyclone',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => null,
                'kapasitas' => '30 ton TBS / jam',
                'tahun_perolehan' => '2013',
                'nomor_inventaris' => '220000005551',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '90',
            ],
            [
                'nama' => 'Fibre Cyclone',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => null,
                'kapasitas' => '30 ton TBS / jam',
                'tahun_perolehan' => '2014',
                'nomor_inventaris' => '220000005456',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '90',
            ],
        ],
        [
            [
                'nama' => 'Ripple Mill',
                'nomor_mesin' => '1',
                'merek' => 'MSB',
                'type' => null,
                'kapasitas' => '6 ton Noten/jam',
                'tahun_perolehan' => '2020',
                'nomor_inventaris' => '220000014558',
                'nilai_aktiva' => '77.962.500',
                'kondisi_mesin' => '85',
            ],
            [
                'nama' => 'Ripple Mill',
                'nomor_mesin' => '2',
                'merek' => 'HJ',
                'type' => null,
                'kapasitas' => '6 ton Noten/jam',
                'tahun_perolehan' => '2015',
                'nomor_inventaris' => '220000005485',
                'nilai_aktiva' => '5.052.187',
                'kondisi_mesin' => '85',
            ],
            [
                'nama' => 'LTDS I',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => null,
                'kapasitas' => '30 ton TBS / jam',
                'tahun_perolehan' => '2014',
                'nomor_inventaris' => '220000005532',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'LTDS II',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => null,
                'kapasitas' => '30 ton TBS / jam',
                'tahun_perolehan' => '2015',
                'nomor_inventaris' => '220000005480',
                'nilai_aktiva' => '11.608.462',
                'kondisi_mesin' => '65',
            ],
            [
                'nama' => 'Claybath',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => null,
                'kapasitas' => '30 ton TBS / jam',
                'tahun_perolehan' => '2009',
                'nomor_inventaris' => '220000005454',
                'nilai_aktiva' => '66.874.115',
                'kondisi_mesin' => '65',
            ],
            [
                'nama' => 'Kernel Drier',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => 'Vertikal',
                'kapasitas' => '30 ton',
                'tahun_perolehan' => '1980',
                'nomor_inventaris' => '220000005428',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '75',
            ],
            [
                'nama' => 'Kernel Drier',
                'nomor_mesin' => '3',
                'merek' => null,
                'type' => 'Vertikal',
                'kapasitas' => '30 ton',
                'tahun_perolehan' => '1980',
                'nomor_inventaris' => '220000005429',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '75',
            ],
            [
                'nama' => 'Bunker Inti',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Vertikal',
                'kapasitas' => '100 ton',
                'tahun_perolehan' => '2012',
                'nomor_inventaris' => '220000005321',
                'nilai_aktiva' => '336.330.158',
                'kondisi_mesin' => '80',
            ],
        ],
        [
            [
                'nama' => 'Ketel Uap',
                'nomor_mesin' => '1',
                'merek' => 'Takuma',
                'type' => 'N-600 SH',
                'kapasitas' => '22 ton uap/jam',
                'tahun_perolehan' => '2020',
                'nomor_inventaris' => '220000014376',
                'nilai_aktiva' => '3.745.250.000',
                'kondisi_mesin' => '85',
            ],
            [
                'nama' => 'Ketel Uap',
                'nomor_mesin' => '2',
                'merek' => 'Takuma',
                'type' => 'N-600 SH',
                'kapasitas' => '20 ton uap/jam',
                'tahun_perolehan' => '1988',
                'nomor_inventaris' => '220000005115',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '40',
            ],
        ],
        [
            [
                'nama' => 'Turbin Uap',
                'nomor_mesin' => '1',
                'merek' => 'Shinko',
                'type' => 'RB4M',
                'kapasitas' => '800 kw',
                'tahun_perolehan' => '2017',
                'nomor_inventaris' => '220000005214',
                'nilai_aktiva' => '3.174.397.037',
                'kondisi_mesin' => '70',
            ],
            [
                'nama' => 'Turbin Uap',
                'nomor_mesin' => '2',
                'merek' => 'Dresser Rand',
                'type' => null,
                'kapasitas' => '800 kw',
                'tahun_perolehan' => '2010',
                'nomor_inventaris' => null,
                'nilai_aktiva' => '1.261.339.753',
                'kondisi_mesin' => '65',
            ],
            [
                'nama' => 'BPV',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '1987',
                'nomor_inventaris' => '220000005207',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '70',
            ],
            [
                'nama' => 'BPV',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '1987',
                'nomor_inventaris' => '220000005208',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '70',
            ],
            [
                'nama' => 'Genset',
                'nomor_mesin' => '1',
                'merek' => 'Cummins',
                'type' => 'Diesel',
                'kapasitas' => '511 kva',
                'tahun_perolehan' => '2003',
                'nomor_inventaris' => '220000005209',
                'nilai_aktiva' => '32.379.021',
                'kondisi_mesin' => '68',
            ],
        ],
        [
            [
                'nama' => 'Sand Filter',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => null,
                'kapasitas' => '3500 liter',
                'tahun_perolehan' => '1990',
                'nomor_inventaris' => '220000005189',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '90',
            ],
            [
                'nama' => 'Sand Filter',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => null,
                'kapasitas' => '3500 liter',
                'tahun_perolehan' => '1990',
                'nomor_inventaris' => '220000005190',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '90',
            ],
            [
                'nama' => 'Sand Filter',
                'nomor_mesin' => '3',
                'merek' => null,
                'type' => null,
                'kapasitas' => '3500 liter',
                'tahun_perolehan' => '1990',
                'nomor_inventaris' => '220000005191',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '90',
            ],
            [
                'nama' => 'Tanki Cation Line I',
                'nomor_mesin' => '1',
                'merek' => 'Exchannger',
                'type' => null,
                'kapasitas' => '1600 liter',
                'tahun_perolehan' => '1989',
                'nomor_inventaris' => '220000005167',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Tanki Anion Line I',
                'nomor_mesin' => '1',
                'merek' => 'Exchannger',
                'type' => null,
                'kapasitas' => '2200 liter',
                'tahun_perolehan' => '1989',
                'nomor_inventaris' => '220000005169',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Tanki Cation Line II',
                'nomor_mesin' => '2',
                'merek' => 'Hydrex',
                'type' => null,
                'kapasitas' => '1600 liter',
                'tahun_perolehan' => '2013',
                'nomor_inventaris' => '220000005560',
                'nilai_aktiva' => '467.898.708',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Tanki Anion Line II',
                'nomor_mesin' => '2',
                'merek' => 'Hydrex',
                'type' => null,
                'kapasitas' => '2200 liter',
                'tahun_perolehan' => '2013',
                'nomor_inventaris' => '220000005560',
                'nilai_aktiva' => '467.898.708',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Feed Water Tank',
                'nomor_mesin' => null,
                'merek' => null,
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => null,
                'nomor_inventaris' => null,
                'nilai_aktiva' => null,
                'kondisi_mesin' => '80',
            ],
        ],
        [
            [
                'nama' => ' TANGKI TIMBUN NO.1',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => null,
                'kapasitas' => '500 Ton',
                'tahun_perolehan' => '1927',
                'nomor_inventaris' => '220000005497',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '25',
            ],
            [
                'nama' => ' TANGKI TIMBUN NO.2',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => null,
                'kapasitas' => '340 Ton',
                'tahun_perolehan' => '1931',
                'nomor_inventaris' => '220000005498',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '25',
            ],
            [
                'nama' => ' TANGKI TIMBUN NO.3',
                'nomor_mesin' => '3',
                'merek' => null,
                'type' => null,
                'kapasitas' => '500 Ton',
                'tahun_perolehan' => '1930',
                'nomor_inventaris' => '220000005499',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => ' TANGKI TIMBUN NO.4',
                'nomor_mesin' => '4',
                'merek' => null,
                'type' => null,
                'kapasitas' => '500 Ton',
                'tahun_perolehan' => '1932',
                'nomor_inventaris' => '220000005500',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '25',
            ],
            [
                'nama' => ' TANGKI TIMBUN NO.5',
                'nomor_mesin' => '5',
                'merek' => null,
                'type' => null,
                'kapasitas' => '1500 Ton',
                'tahun_perolehan' => '1932',
                'nomor_inventaris' => '220000005501',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => null,
            ],
            [
                'nama' => ' TANGKI TIMBUN NO.6',
                'nomor_mesin' => '6',
                'merek' => null,
                'type' => null,
                'kapasitas' => '500 Ton',
                'tahun_perolehan' => '1932',
                'nomor_inventaris' => '220000005502',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => ' TANGKI TIMBUN NO.7',
                'nomor_mesin' => '7',
                'merek' => null,
                'type' => null,
                'kapasitas' => '500 Ton',
                'tahun_perolehan' => '1932',
                'nomor_inventaris' => '220000005503',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '25',
            ],
            [
                'nama' => ' TANGKI TIMBUN NO.8',
                'nomor_mesin' => '8',
                'merek' => null,
                'type' => null,
                'kapasitas' => '1500 Ton',
                'tahun_perolehan' => '1940',
                'nomor_inventaris' => '220000005504',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => ' TANGKI TIMBUN NO.10',
                'nomor_mesin' => '10',
                'merek' => null,
                'type' => null,
                'kapasitas' => '1500 Ton',
                'tahun_perolehan' => '1934',
                'nomor_inventaris' => '220000005505',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
        ],
        [
            [
                'nama' => 'Scrapper Mendaki Tandan Kosong',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => 'Scrapper',
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2016',
                'nomor_inventaris' => '220000005202',
                'nilai_aktiva' => '69.449.000',
                'kondisi_mesin' => '70',
            ],
            [
                'nama' => 'Hopper Tandan Kosong (3 pintu)',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Kompartment',
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2020',
                'nomor_inventaris' => '220000014636',
                'nilai_aktiva' => '377.910.681',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Hopper Tandan Kosong (2 pintu)',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => 'Kompartment',
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2021',
                'nomor_inventaris' => '220000015096',
                'nilai_aktiva' => ' 434.598.417 ',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Scrapper Mendatar Hopper Tankos',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'Scrapper',
                'kapasitas' => '30 ton TBS/jam',
                'tahun_perolehan' => '2018',
                'nomor_inventaris' => '220000005296',
                'nilai_aktiva' => '85.879.924',
                'kondisi_mesin' => '80',
            ],
        ],
        [
            [
                'nama' => 'Pipa Distribusi LCKS',
                'nomor_mesin' => null,
                'merek' => null,
                'type' => 'Pipa',
                'kapasitas' => '20 m3/jam',
                'tahun_perolehan' => '2020',
                'nomor_inventaris' => '220000014099',
                'nilai_aktiva' => '316.329.271',
                'kondisi_mesin' => '65',
            ],
        ],
        [
            [
                'nama' => 'TIMBANGAN DUDUK 50 KG',
                'nomor_mesin' => '1',
                'merek' => 'Kubota',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2013',
                'nomor_inventaris' => '240000002350',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'OVEN 0-250⁰C',
                'nomor_mesin' => '1',
                'merek' => 'Memmert',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2013',
                'nomor_inventaris' => '240000002359',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'PH-METER',
                'nomor_mesin' => '1',
                'merek' => 'BENCH',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2013',
                'nomor_inventaris' => '240000002356',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'LOVIBOND COMPARATOR WITH DISC',
                'nomor_mesin' => '1',
                'merek' => 'Nesslenzer',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2013',
                'nomor_inventaris' => '240000002353',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '50',
            ],
            [
                'nama' => 'CENTRIFUGE',
                'nomor_mesin' => '1',
                'merek' => 'Hettich',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2010',
                'nomor_inventaris' => '240000002347',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'HOT PLATE (6TUNGKU)',
                'nomor_mesin' => '1',
                'merek' => 'Gerhard',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2016',
                'nomor_inventaris' => '240000002361',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '85',
            ],
            [
                'nama' => 'HOT PLATE (6TUNGKU)',
                'nomor_mesin' => '2',
                'merek' => 'Gerhard',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2021',
                'nomor_inventaris' => '2,4E+11',
                'nilai_aktiva' => '59.103.000',
                'kondisi_mesin' => '95',
            ],
            [
                'nama' => 'GILINGAN INTI/KERNEL',
                'nomor_mesin' => '1',
                'merek' => 'Apec Contruction',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2013',
                'nomor_inventaris' => '240000002358',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '85',
            ],
            [
                'nama' => 'TDS-METER',
                'nomor_mesin' => '1',
                'merek' => 'HANNA',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2013',
                'nomor_inventaris' => '240000002360',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '85',
            ],
            [
                'nama' => 'TIMBANGAN ANALITIK 210 GR',
                'nomor_mesin' => '1',
                'merek' => 'Sartorius',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2007',
                'nomor_inventaris' => '240000002341',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'TIMBANGAN DIGITAL 12 KG',
                'nomor_mesin' => '1',
                'merek' => 'And gp - 12K',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2011',
                'nomor_inventaris' => '240000002349',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'MOUISTURE BALANCE',
                'nomor_mesin' => '1',
                'merek' => 'Adam',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2013',
                'nomor_inventaris' => '240000002357',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '50',
            ],
            [
                'nama' => 'Foss Nirs',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => 'DA 1650',
                'kapasitas' => null,
                'tahun_perolehan' => '2021',
                'nomor_inventaris' => '240000014533',
                'nilai_aktiva' => '473.000.000',
                'kondisi_mesin' => '95',
            ],
        ],
        [
            [
                'nama' => 'Mesin Scrap',
                'nomor_mesin' => '1',
                'merek' => 'Invicta',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2013',
                'nomor_inventaris' => '220000005513',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Mesin Frais',
                'nomor_mesin' => '1',
                'merek' => 'VICTORIA',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '1997',
                'nomor_inventaris' => '220000005514',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '50',
            ],
            [
                'nama' => 'Mesin Bubut',
                'nomor_mesin' => '1',
                'merek' => 'Boshi',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2012',
                'nomor_inventaris' => '240000002318',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '65',
            ],
            [
                'nama' => 'Mesin Gergaji',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '1997',
                'nomor_inventaris' => '220000005517',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '70',
            ],
            [
                'nama' => 'MESIN STEEK RODA GIGI.',
                'nomor_mesin' => '1',
                'merek' => 'TOKYO JAPAN',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '1998',
                'nomor_inventaris' => '220000005519',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '75',
            ],
            [
                'nama' => 'MESIN BOR BESAR',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2016',
                'nomor_inventaris' => '240000002320',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '80',
            ],
            [
                'nama' => 'Trafo Las',
                'nomor_mesin' => '1',
                'merek' => null,
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2020',
                'nomor_inventaris' => '220000013987',
                'nilai_aktiva' => '35.867.883',
                'kondisi_mesin' => '75',
            ],
            [
                'nama' => 'Trafo Las',
                'nomor_mesin' => '2',
                'merek' => null,
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2020',
                'nomor_inventaris' => '220000013988',
                'nilai_aktiva' => '35.867.883',
                'kondisi_mesin' => '75',
            ],
            [
                'nama' => 'Trafo Las',
                'nomor_mesin' => '3',
                'merek' => null,
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2016',
                'nomor_inventaris' => '240000002321',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '65',
            ],
            [
                'nama' => 'Trafo Las',
                'nomor_mesin' => '4',
                'merek' => 'SUN',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2008',
                'nomor_inventaris' => '240000002313',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '65',
            ],
            [
                'nama' => 'Trafo Las',
                'nomor_mesin' => '5',
                'merek' => 'SUN',
                'type' => null,
                'kapasitas' => null,
                'tahun_perolehan' => '2008',
                'nomor_inventaris' => '240000002314',
                'nilai_aktiva' => '1',
                'kondisi_mesin' => '55',
            ],
        ],
    ];
    public function run(): void
    {
        $i = 0;
        foreach ($this->mesin as $arr) {
            $i++;
            foreach ($arr as $item) { 
                inventaris::create([
                    'nama' => $item['nama'],
                    'nomor_mesin' => $item['nomor_mesin'],
                    'merek' => $item['merek'],
                    'type' => $item['type'],
                    'kapasitas' => $item['kapasitas'],
                    'tahun_perolehan' => $item['tahun_perolehan'],
                    'nomor_inventaris' => $item['nomor_inventaris'],
                    'nilai_aktiva' => $item['nilai_aktiva'],
                    'kondisi_mesin' => $item['kondisi_mesin'],
                    'category_id' => $i  ,
                    'user_id' => 1,
                ]);
            }
        }
        // for ($i=0; $i < count($this->mesin) ; $i++) {
        //     for ($j=0; $j < count($this->mesin[$i]) ; $j++) {
        //         inventaris::create([
        //             'nama' => $this->mesin[$i][$j][0],
        //             'nomor_mesin' => $this->mesin[$i][$j][1],
        //             'merek' => $this->mesin[$i][$j][2],
        //             'type' => $this->mesin[$i][$j][3],
        //             'kapasitas' => $this->mesin[$i][$j][4],
        //             'tahun_perolehan' => $this->mesin[$i][$j][5],
        //             'nomor_inventaris' => $this->mesin[$i][$j][6],
        //             'nilai_aktiva' => $this->mesin[$i][$j][7],
        //             'kondisi_mesin' => $this->mesin[$i][$j][8],
        //             'category_id' => $i +1,
        //             'user_id' => 1,
        //         ]);
        //     }
        // }
    }
}
